In [42]:
import pandas as pd

data=pd.read_csv("D:\\shivani\\data science\\pandas\\E-commerce_Sales\\customers.csv")
data

data.head(10)
data.tail(10)
data.info()
data.describe()
data.isnull().sum()
data.duplicated().sum()

new_data=data.copy()
new_data["Age"]=new_data["Age"].fillna(new_data["Age"].mean())
print(new_data.isnull().sum())

new_data["City"]=new_data["City"].fillna("Unknown")
print(new_data.isnull().sum())
new_data

new_data["SignupDate"]=pd.to_datetime(new_data["SignupDate"])
new_data.info()

new_data["City"].value_counts()
new_data["CustomerSegment"].value_counts()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       10000 non-null  int64
 1   Age              9820 non-null   float64
 2   City             9881 non-null   str
 3   SignupDate       10000 non-null  str
 4   CustomerSegment  10000 non-null  str
dtypes: float64(1), int64(1), str(3)
memory usage: 597.2 KB
CustomerID           0
Age                  0
City               119
SignupDate           0
CustomerSegment      0
dtype: int64
CustomerID         0
Age                0
City               0
SignupDate         0
CustomerSegment    0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       10000 non-null  int64
 1   Age              10000 non-null  float64
 2   City             10000 non-null  str
 3   SignupDate       10000 non-null  datetime64[us]
 4   CustomerSegment  10000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 499.1 KB

CustomerSegment
Regular    5563
New        3462
VIP         975
Name: count, dtype: int64

In [62]:
new_data=new_data.assign(
    SignupYear=new_data["SignupDate"].dt.year,
    SignupMonth=new_data["SignupDate"].dt.month,
    SignupDay=new_data["SignupDate"].dt.day,
    SignupDayOfWeek=new_data["SignupDate"].dt.day_name()
)
new_data

,CustomerID,Age,City,SignupDate,CustomerSegment,SignupYear,SignupMonth,SignupDay,SignupDayOfWeek
0,100001,22.0,Tehran,2023-09-11,Regular,2023,9,11,Monday
1,100002,55.0,Tabriz,2024-01-16,VIP,2024,1,16,Tuesday
2,100003,49.0,Karaj,2025-07-31,New,2025,7,31,Thursday
3,100004,39.0,Tehran,2023-04-23,New,2023,4,23,Sunday
4,100005,38.0,Tehran,2023-04-29,Regular,2023,4,29,Saturday
...,...,...,...,...,...,...,...,...,...
9995,109996,40.0,Ahvaz,2025-07-16,Regular,2025,7,16,Wednesday
9996,109997,65.0,Shiraz,2023-09-20,Regular,2023,9,20,Wednesday
9997,109998,34.0,Tehran,2025-01-04,Regular,2025,1,4,Saturday
9998,109999,45.0,Mashhad,2023-02-13,VIP,2023,2,13,Monday
9999,110000,47.0,Ahvaz,2023-06-04,New,2023,6,4,Sunday

In [68]:
avg_age=new_data.groupby("CustomerSegment")["Age"].agg(avg_age="mean")
avg_age

city_count=new_data.groupby('City')['CustomerID'].count()
city_count

avg_city_age=new_data.groupby('City')['Age'].mean()
avg_city_age

City
Ahvaz      41.285349
Isfahan    40.908399
Karaj      41.263610
Kerman     41.534904
Mashad     41.200000
Mashhad    40.964745
Qom        41.347625
Rasht      42.040243
Shiraz     41.450290
Tabriz     41.193534
Tehran     41.470690
Unknown    41.422571
tehran     41.071429
Name: Age, dtype: float64

In [18]:
data2=pd.read_csv("D:\\shivani\\data science\\pandas\\E-commerce_Sales\\orders.csv")
order_data=data2.copy()
order_data.info()
order_data.isnull().sum()
order_data["PaymentMethod"]=order_data["PaymentMethod"].fillna("Not Specified")
order_data["PaymentMethod"]
order_data["Discount"] = order_data["Discount"].fillna(
    order_data["Discount"].median()
)


order_data["Quantity"].describe()
(order_data["Quantity"] < 0).sum()
order_data[order_data["Quantity"] < 0][["OrderID", "CustomerID", "Quantity", "Status"]]
order_data[order_data["Quantity"] < 0]["Quantity"].value_counts()
order_data.loc[order_data["Quantity"]<0,"Quantity"]=pd.NA
order_data["Quantity"].isnull().sum()
order_data["Quantity"]=order_data["Quantity"].fillna(order_data["Quantity"].median())
order_data["Quantity"].isnull().sum()


order_data["OrderDate"]=pd.to_datetime(order_data["OrderDate"],errors="coerce")
order_data["OrderDate"]
order_data["OrderDate"].isnull().sum()
order_data[order_data["OrderDate"].isnull()][["OrderID", "CustomerID", "Quantity", "Status"]]

#Check whether the same CustomerID has other orders with known dates
missing_dates=order_data[order_data["OrderDate"].isna()]
order_data[
    order_data["CustomerID"].isin(missing_dates["CustomerID"])][["OrderID", "CustomerID","OrderDate","Quantity", "Status"]].sort_values(["CustomerID", "OrderDate"])

print(missing_dates["CustomerID"].value_counts())
missing_dates[["OrderID", "CustomerID", "ProductID", "Quantity", "Status"]]

#OrderDate: 35 values were missing.Since the actual order dates could not be reliably determined from the available data, 
#the missing values were retained as NaT rather than assigning arbitrary dates.

<class 'pandas.DataFrame'>
RangeIndex: 50120 entries, 0 to 50119
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        50120 non-null  int64
 1   CustomerID     50120 non-null  int64
 2   OrderDate      50085 non-null  str
 3   ProductID      50120 non-null  int64
 4   Quantity       50040 non-null  float64
 5   Discount       49899 non-null  float64
 6   PaymentMethod  49668 non-null  str
 7   Status         50120 non-null  str
dtypes: float64(2), int64(3), str(3)
memory usage: 4.3 MB
CustomerID
102438    1
102111    1
103942    1
104260    1
100075    1
106056    1
102701    1
109841    1
100699    1
109973    1
103600    1
103693    1
108660    1
109568    1
100139    1
102500    1
106073    1
107146    1
104895    1
104480    1
103491    1
101891    1
101067    1
104443    1
104803    1
108459    1
105799    1
104846    1
100455    1
109466    1
108570    1
106685    1
101707    1
106816    1
109134    1
Name: count, dtype: int64

       OrderID  CustomerID  ProductID  Quantity     Status
2355    502356      102438       2013       4.0  Completed
4926    504927      102111       2004       1.0  Completed
5564    505565      103942       2003       2.0  Completed
6267    506268      104260       2013       1.0  Completed
7647    507648      100075       2013       2.0  Completed
7859    507860      106056       2008       3.0  Completed
9136    509137      102701       2013       2.0  Completed
10412   510413      109841       2006       4.0  Completed
10559   510560      100699       2013       1.0  Completed
14165   514166      109973       2013       4.0  Completed
16434   516435      103600       2003       1.0  Completed
17957   517958      103693       2017       4.0  Completed
18120   518121      108660       2013       4.0  Completed
18599   518600      109568       2004       2.0  Completed
22527   522528      100139       2001       1.0  Completed
24983   524984      102500       2005       2.0  Completed
25084   525085      106073       2006       1.0  Completed
25706   525707      107146       2007       1.0  Completed
26840   526841      104895       2010       1.0  Completed
27947   527948      104480       2004       4.0   Returned
27980   527981      103491       2005       1.0  Completed
28316   528317      101891       2014       4.0  Completed
29081   529082      101067       2005       1.0  Completed
30837   530838      104443       2009       2.0  Completed
32695   532696      104803       2011       1.0  Completed
33351   533352      108459       2004       1.0  Completed
33796   533797      105799       2004       3.0  Completed
34249   534250      104846       2004       1.0  Completed
34608   534609      100455       2008       2.0  Cancelled
37795   537796      109466       2015       2.0  Completed
38862   538863      108570       2020       1.0  Completed
42657   542658      106685       2013       3.0  Completed
46602   546603      101707       2016       3.0  Completed
48266   548267      106816       2004       1.0  Completed
49141   549142      109134       2010       1.0  Completed

In [29]:
data=pd.read_csv("D:\\shivani\\data science\\pandas\\E-commerce_Sales\\payments.csv")
payments_data=data.copy()
payments_data.info()
payments_data.isnull().sum()
payments_data["PaymentDate"]=pd.to_datetime(payments_data["PaymentDate"])
payments_data.info()
payments_data.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PaymentID      50000 non-null  int64
 1   OrderID        50000 non-null  int64
 2   PaymentDate    49965 non-null  str
 3   PaymentStatus  50000 non-null  str
dtypes: int64(2), str(2)
memory usage: 2.2 MB
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PaymentID      50000 non-null  int64
 1   OrderID        50000 non-null  int64
 2   PaymentDate    49965 non-null  datetime64[us]
 3   PaymentStatus  50000 non-null  str
dtypes: datetime64[us](1), int64(2), str(1)
memory usage: 1.7 MB

np.int64(0)

In [41]:
data=pd.read_csv("D:\\shivani\\data science\\pandas\\E-commerce_Sales\\products.csv")
products_data=data.copy()
products_data.info()
products_data.isnull().sum()
products_data.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    20 non-null     int64
 1   ProductName  20 non-null     str
 2   Category     20 non-null     str
 3   UnitPrice    20 non-null     float64
dtypes: float64(1), int64(1), str(2)
memory usage: 1.2 KB

np.int64(0)

In [46]:
new_data
new_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       10000 non-null  int64
 1   Age              10000 non-null  float64
 2   City             10000 non-null  str
 3   SignupDate       10000 non-null  datetime64[us]
 4   CustomerSegment  10000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 499.1 KB

In [61]:
order_data
order_data.info()
order_data["OrderID"].duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 50120 entries, 0 to 50119
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        50120 non-null  int64
 1   CustomerID     50120 non-null  int64
 2   OrderDate      50085 non-null  datetime64[us]
 3   ProductID      50120 non-null  int64
 4   Quantity       50120 non-null  float64
 5   Discount       50120 non-null  float64
 6   PaymentMethod  50120 non-null  str
 7   Status         50120 non-null  str
dtypes: datetime64[us](1), float64(2), int64(3), str(2)
memory usage: 3.8 MB

0

In [50]:
payments_data
payments_data.info()
payments_data["OrderID"].duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PaymentID      50000 non-null  int64
 1   OrderID        50000 non-null  int64
 2   PaymentDate    49965 non-null  datetime64[us]
 3   PaymentStatus  50000 non-null  str
dtypes: datetime64[us](1), int64(2), str(1)
memory usage: 1.7 MB

np.int64(0)

In [47]:
products_data
products_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    20 non-null     int64
 1   ProductName  20 non-null     str
 2   Category     20 non-null     str
 3   UnitPrice    20 non-null     float64
dtypes: float64(1), int64(1), str(2)
memory usage: 1.2 KB

In [63]:
order_ids=set(order_data["OrderID"])
payments_order_ids=set(payments_data["OrderID"])
missing_payment_orders=order_ids-payments_order_ids

len(missing_payment_orders)

missing_order_dates=order_data[order_data["OrderDate"].isna()]
missing_payment_dates=payments_data[payments_data["PaymentDate"].isna()]

missing_order_dates["OrderID"].isin(missing_payment_dates["OrderID"]).sum()
#The 35 missing order dates and 35 missing payment dates correspond to the same orders.
#Since no reliable source is available to reconstruct those dates, they were retained as missing.

np.int64(35)

In [75]:
# merging Order + Customer
order_customer=order_data.merge(
    new_data,
    on="CustomerID",
    how="left"
)
order_customer.shape
order_customer["CustomerID"].isna().sum()
order_customer

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment
0,500001,103695,2025-08-28,2003,4.0,0.10,Gateway,Completed,36.0,Qom,2024-03-05,Regular
1,500002,107935,2024-05-31,2014,1.0,0.10,Wallet,Completed,49.0,Kerman,2025-06-04,Regular
2,500003,105141,2025-08-10,2002,1.0,0.20,CardToCard,Completed,36.0,Tehran,2025-10-19,Regular
3,500004,108780,2024-10-11,2012,1.0,0.10,Gateway,Completed,45.0,Shiraz,2023-12-07,Regular
4,500005,101187,2024-02-19,2008,2.0,0.00,Gateway,Completed,24.0,Karaj,2023-12-02,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...
50115,546916,106069,2024-11-08,2003,1.0,0.10,CardToCard,Completed,25.0,Isfahan,2024-05-15,New
50116,509802,107180,2024-09-19,2012,1.0,0.10,CardToCard,Completed,32.0,tehran,2023-01-06,Regular
50117,538801,109723,2025-02-19,2006,2.0,0.05,Wallet,Completed,23.0,Karaj,2023-10-20,New
50118,524670,108719,2025-08-08,2013,1.0,0.05,Gateway,Completed,48.0,Tabriz,2023-09-09,Regular
50119,544234,106789,2024-04-03,2003,1.0,0.00,Gateway,Completed,29.0,Karaj,2025-05-06,New

In [71]:
# merging Order + Customer + products
order_customer_product=order_customer.merge(
    products_data,
    on="ProductID",
    how="left"
)
order_customer_product

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice
0,500001,103695,2025-08-28,2003,4.0,0.10,Gateway,Completed,36.0,Qom,2024-03-05,Regular,USB-C Cable,Accessories,9.0
1,500002,107935,2024-05-31,2014,1.0,0.10,Wallet,Completed,49.0,Kerman,2025-06-04,Regular,Backpack,Accessories,42.0
2,500003,105141,2025-08-10,2002,1.0,0.20,CardToCard,Completed,36.0,Tehran,2025-10-19,Regular,Mechanical Keyboard,Electronics,62.0
3,500004,108780,2024-10-11,2012,1.0,0.10,Gateway,Completed,45.0,Shiraz,2023-12-07,Regular,Office Chair,Home Office,180.0
4,500005,101187,2024-02-19,2008,2.0,0.00,Gateway,Completed,24.0,Karaj,2023-12-02,Regular,Phone Case,Accessories,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50115,546916,106069,2024-11-08,2003,1.0,0.10,CardToCard,Completed,25.0,Isfahan,2024-05-15,New,USB-C Cable,Accessories,9.0
50116,509802,107180,2024-09-19,2012,1.0,0.10,CardToCard,Completed,32.0,tehran,2023-01-06,Regular,Office Chair,Home Office,180.0
50117,538801,109723,2025-02-19,2006,2.0,0.05,Wallet,Completed,23.0,Karaj,2023-10-20,New,Webcam,Electronics,48.0
50118,524670,108719,2025-08-08,2013,1.0,0.05,Gateway,Completed,48.0,Tabriz,2023-09-09,Regular,Notebook,Stationery,7.0
50119,544234,106789,2024-04-03,2003,1.0,0.00,Gateway,Completed,29.0,Karaj,2025-05-06,New,USB-C Cable,Accessories,9.0

In [74]:
#merging Order + Customer + products + payments
full_data = order_customer_product.merge(
    payments_data,
    on="OrderID",
    how="left"
)
full_data

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice,PaymentID,PaymentDate,PaymentStatus
0,500001,103695,2025-08-28,2003,4.0,0.10,Gateway,Completed,36.0,Qom,2024-03-05,Regular,USB-C Cable,Accessories,9.0,800001,2025-08-28,Paid
1,500002,107935,2024-05-31,2014,1.0,0.10,Wallet,Completed,49.0,Kerman,2025-06-04,Regular,Backpack,Accessories,42.0,800002,2024-05-31,Paid
2,500003,105141,2025-08-10,2002,1.0,0.20,CardToCard,Completed,36.0,Tehran,2025-10-19,Regular,Mechanical Keyboard,Electronics,62.0,800003,2025-08-10,Paid
3,500004,108780,2024-10-11,2012,1.0,0.10,Gateway,Completed,45.0,Shiraz,2023-12-07,Regular,Office Chair,Home Office,180.0,800004,2024-10-11,Paid
4,500005,101187,2024-02-19,2008,2.0,0.00,Gateway,Completed,24.0,Karaj,2023-12-02,Regular,Phone Case,Accessories,14.0,800005,2024-02-19,Paid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50115,546916,106069,2024-11-08,2003,1.0,0.10,CardToCard,Completed,25.0,Isfahan,2024-05-15,New,USB-C Cable,Accessories,9.0,846916,2024-11-08,Paid
50116,509802,107180,2024-09-19,2012,1.0,0.10,CardToCard,Completed,32.0,tehran,2023-01-06,Regular,Office Chair,Home Office,180.0,809802,2024-09-19,Paid
50117,538801,109723,2025-02-19,2006,2.0,0.05,Wallet,Completed,23.0,Karaj,2023-10-20,New,Webcam,Electronics,48.0,838801,2025-02-19,Paid
50118,524670,108719,2025-08-08,2013,1.0,0.05,Gateway,Completed,48.0,Tabriz,2023-09-09,Regular,Notebook,Stationery,7.0,824670,2025-08-08,Paid
50119,544234,106789,2024-04-03,2003,1.0,0.00,Gateway,Completed,29.0,Karaj,2025-05-06,New,USB-C Cable,Accessories,9.0,844234,2024-04-03,Paid

In [81]:
#1. Sales & Order Analysis

#How many total orders are there?
full_data["OrderID"].nunique()
#Which month has the most orders?
full_data.groupby(full_data["OrderDate"].dt.month)["OrderID"].nunique().idxmax()
#Most common order status
full_data["Status"].value_counts()

Status
Completed    46105
Cancelled     2477
Returned      1538
Name: count, dtype: int64

In [85]:
#Customer Analysis

#Which customer segment places the most orders?
full_data.groupby(full_data["CustomerSegment"])["OrderID"].nunique().idxmax()

'Regular'