In [2]:
import pandas as pd

In [20]:
#apply() is useful when you want to perform a custom transformation.
data={
    "Names":["shivani","abhishek","saurabh"],
    "Age":[20,26,28],
    "salary":[20000,50000,70000]
}
df=pd.DataFrame(data)

def age_group(Age):
    if Age<25:
        return "young"
    else:
        return "adult"

df["Age_group"]=df["Age"].apply(age_group)
print(df["Age_group"])


#apply method with lambda...
df["increased_saraly"]=df["salary"].apply(lambda x:x + 1000 if x<60000 else x)
print(df["increased_saraly"])
print(df)

0    young
1    adult
2    adult
Name: Age_group, dtype: str
0    21000
1    51000
2    70000
Name: increased_saraly, dtype: int64
      Names  Age  salary Age_group  increased_saraly
0   shivani   20   20000     young             21000
1  abhishek   26   50000     adult             51000
2   saurabh   28   70000     adult             70000

In [19]:
#map() is especially useful for categorical data.
data={
    "Names":["shivani","abhishek","saurabh"],
    "Age":[20,26,28],
    "salary":[20000,50000,70000],
    "gender":["female","male","male"]
}
df=pd.DataFrame(data)

df["gender_code"]=df["gender"].map({
    "female":1,
    "male":0
})
print(df["gender_code"])
print(df)

0    1
1    0
2    0
Name: gender_code, dtype: int64
      Names  Age  salary  gender  gender_code
0   shivani   20   20000  female            1
1  abhishek   26   50000    male            0
2   saurabh   28   70000    male            0

In [25]:
#assign- (is useful for creating new features while keeping your DataFrame transformation clean.)

data={
    "Names":["shivani","abhishek","saurabh"],
    "Age":[20,26,28],
    "salary":[20000,50000,70000],
    "gender":["female","male","male"]
}
df=pd.DataFrame(data)
df=df.assign(
    gender_code=df["gender"].map({"female":0,"male":1})
)
print(df)

      Names  Age  salary  gender  gender_code
0   shivani   20   20000  female            0
1  abhishek   26   50000    male            1
2   saurabh   28   70000    male            1

In [26]:
#replace
data={
    "Names":["shivani","abhishek","saurabh"],
    "Age":[20,26,28],
    "salary":[20000,50000,70000],
    "gender":["female","male","male"]
}
df=pd.DataFrame(data)

df["Names"]=df["Names"].replace("shivani","shivani kumari")
print(df)

            Names  Age  salary  gender
0  shivani kumari   20   20000  female
1        abhishek   26   50000    male
2         saurabh   28   70000    male

In [32]:
#rename
df.rename(columns={"salary":"Income"})
df.rename(columns={"gender":"Gender"})

df.rename(index={1:"first"})

                Names  Age  salary  gender
0      shivani kumari   20   20000  female
first        abhishek   26   50000    male
2             saurabh   28   70000    male

In [19]:
df=pd.read_csv("titanic/train.csv")
df2=df.copy()
df2
df2.sort_values("Age",ascending=False)
df2.sort_values(["Age","Fare"])
df2.sort_index()
df2.reset_index()
df2.reset_index(drop=True)
df2["ranking"]=df2["Fare"].rank()
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ranking
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,77.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,789.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,232.5
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,748.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,264.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,407.5
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,654.5
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,546.5
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,654.5
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,123.5

In [22]:
# reorder values
df2[["PassengerId","Age","SibSp","Parch","Ticket","Fare",
    "Survived","Pclass","Name","Sex","Cabin","Embarked","ranking"]]

,PassengerId,Age,SibSp,Parch,Ticket,Fare,Survived,Pclass,Name,Sex,Cabin,Embarked,ranking
0,1,22.0,1,0,A/5 21171,7.2500,0,3,"Braund, Mr. Owen Harris",male,NaN,S,77.0
1,2,38.0,1,0,PC 17599,71.2833,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,C85,C,789.0
2,3,26.0,0,0,STON/O2. 3101282,7.9250,1,3,"Heikkinen, Miss. Laina",female,NaN,S,232.5
3,4,35.0,1,0,113803,53.1000,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,C123,S,748.0
4,5,35.0,0,0,373450,8.0500,0,3,"Allen, Mr. William Henry",male,NaN,S,264.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,27.0,0,0,211536,13.0000,0,2,"Montvila, Rev. Juozas",male,NaN,S,407.5
887,888,19.0,0,0,112053,30.0000,1,1,"Graham, Miss. Margaret Edith",female,B42,S,654.5
888,889,NaN,1,2,W./C. 6607,23.4500,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,S,546.5
889,890,26.0,0,0,111369,30.0000,1,1,"Behr, Mr. Karl Howell",male,C148,C,654.5
890,891,32.0,0,0,370376,7.7500,0,3,"Dooley, Mr. Patrick",male,NaN,Q,123.5